# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_required: true
warnings_are_errors: true
after_success:
  - Rscript -e 'covr::codecov(type = "all")'

addons:
  apt:
    packages:
    - libgsl0-dev

env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi  
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - source ${fname}; rm ${fname}  
  - gsl_install 2.1 || true ; # now checking version
